# Generated by Django 3.1.5 on 2021-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_gen', '0002_auto_20210113_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='city',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='phone',
        ),
        migrations.AddField(
            model_name='scheme',
            name='c1',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'Name'), ('3', 'Job'), ('4', 'Company'), ('5', 'Date'), ('6', 'E-mail')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
