# Generated by Django 3.1.5 on 2021-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_gen', '0003_auto_20210114_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='c1',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'Name'), ('3', 'Job'), ('4', 'Company'), ('5', 'Date'), ('6', 'E-mail')], default='Choose...', max_length=30),
        ),
    ]
