# Generated by Django 3.1.5 on 2021-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_gen', '0009_auto_20210115_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='c1',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'email')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='c2',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'email')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='c3',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'email')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='c4',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'email')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='c5',
            field=models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'email')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='n1',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='n2',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='n3',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='n4',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='n5',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
    ]
