# Generated by Django 3.1.5 on 2021-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_gen', '0014_auto_20210115_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
